// Code generated by MockGen. DO NOT EDIT.
// Source: bugreport.go

// Package bugreport is a generated GoMock package.
package bugreport

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ersatz "github.com/golang/mock/mockgen/internal/tests/import_embedded_interface/ersatz"
	ersatz0 "github.com/golang/mock/mockgen/internal/tests/import_embedded_interface/other/ersatz"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockSource) Bar() Baz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bar")
	ret0, _ := ret[0].(Baz)
	return ret0
}

// Bar indicates an expected call of Bar.
func (mr *MockSourceMockRecorder) Bar() *SourceBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockSource)(nil).Bar))
	return &SourceBarCall{Call: call}
}

//  SourceBarCall wrap *gomock.Call
type SourceBarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *SourceBarCall) Return(arg0 Baz) *gomock.Call {
	return c.Call.Return(arg0)
}

// Error mocks base method.
func (m *MockSource) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockSourceMockRecorder) Error() *SourceErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSource)(nil).Error))
	return &SourceErrorCall{Call: call}
}

//  SourceErrorCall wrap *gomock.Call
type SourceErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *SourceErrorCall) Return(arg0 string) *gomock.Call {
	return c.Call.Return(arg0)
}

// Ersatz mocks base method.
func (m *MockSource) Ersatz() ersatz.Return {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ersatz")
	ret0, _ := ret[0].(ersatz.Return)
	return ret0
}

// Ersatz indicates an expected call of Ersatz.
func (mr *MockSourceMockRecorder) Ersatz() *SourceErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ersatz", reflect.TypeOf((*MockSource)(nil).Ersatz))
	return &SourceErsatzCall{Call: call}
}

//  SourceErsatzCall wrap *gomock.Call
type SourceErsatzCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *SourceErsatzCall) Return(arg0 ersatz.Return) *gomock.Call {
	return c.Call.Return(arg0)
}

// OtherErsatz mocks base method.
func (m *MockSource) OtherErsatz() ersatz0.Return {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OtherErsatz")
	ret0, _ := ret[0].(ersatz0.Return)
	return ret0
}

// OtherErsatz indicates an expected call of OtherErsatz.
func (mr *MockSourceMockRecorder) OtherErsatz() *SourceOtherErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OtherErsatz", reflect.TypeOf((*MockSource)(nil).OtherErsatz))
	return &SourceOtherErsatzCall{Call: call}
}

//  SourceOtherErsatzCall wrap *gomock.Call
type SourceOtherErsatzCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *SourceOtherErsatzCall) Return(arg0 ersatz0.Return) *gomock.Call {
	return c.Call.Return(arg0)
}
